Repository tqdm/tqdm, pull requests merged in 2019-11, with the labels that each got.

#686 auto-snap
  .travis.yml
Labels: review, to-merge

#713 Add missing isatty() method to DummyTqdmFile
  .meta/.readme.rst
  README.rst
  examples/redirect_print.py
Labels: enhancement, to-merge

#837 Replace dedent calls by dedented strings.
  tqdm/std.py
Labels: bug-perf, to-merge

#854 added a missing import
  README.rst
Labels: question, to-merge
