Repository tqdm/tqdm, pull requests merged in 2020-03, with the labels that each got.

#907 Update Arabic spelling
  .meta/.snapcraft.yml
  DEMO.ipynb
  examples/paper.md
Labels: to-merge

#912 tqdm.contrib.concurrent.process_map: Add 'chunksize' argument
  tqdm/contrib/concurrent.py
  tqdm/tests/tests_concurrent.py
Labels: enhancement, submodule, synchronisation, to-merge

#924 add `nrows`
  README.rst
  tqdm/std.py
  tqdm/tests/tests_tqdm.py
  tqdm/tqdm.1
  tqdm/utils.py
Labels: bug-warning, enhancement, question/docs, synchronisation, to-fix
