Repository tqdm/tqdm, pull requests merged in 2020-06, with the labels that each got.

#978 Fix error due to missing sys.setcheckinterval in py3.9
  tqdm/tests/tests_tqdm.py
Labels: c1-quick, eol, to-merge

#910 Paper: Spell project names as they spell them
  examples/paper.md
Labels: question/docs

#911 Paper: Update impact stats for 2020
  examples/paper.bib
  examples/paper.md
Labels: question/docs

#986 add py38
  .travis.yml
  setup.py
  tox.ini
Labels: to-merge

#976 add contrib.discord: first Discord Bot!
  .coveragerc
  .meta/.readme.rst
  README.rst
  tqdm/cli.py
  tqdm/contrib/discord.py
  tqdm/contrib/telegram.py
  tqdm/contrib/utils_worker.py
  tqdm/utils.py
Labels: p3-enhancement, submodule, to-merge
