Repository tqdm/tqdm, pull requests merged in 2020-09, with the labels that each got.

#1029 fix version detection in auto.py
  tqdm/auto.py
Labels: c1-quick, submodule, to-merge

#1014 cli: add `--tee`
  README.rst
  tqdm/cli.py
  tqdm/completion.sh
  tqdm/tests/tests_main.py
  tqdm/tqdm.1
Labels: c1-quick, p3-enhancement, question/docs, submodule, to-merge

#1021 fix total ETA when using `initial`
  tqdm/std.py
  tqdm/tests/tests_tqdm.py
Labels: c1-quick, p2-bug-warning, to-merge

#996 cli: add --update and --update_to
  .meta/.readme.rst
  Makefile
  README.rst
  tqdm/cli.py
  tqdm/completion.sh
  tqdm/tests/tests_main.py
  tqdm/tqdm.1
Labels: c3-small, p3-enhancement, question/docs, submodule, to-merge

#1032 notebook: fix description width for unknown `total`
  tqdm/notebook.py
Labels: c3-small, p2-bug-warning, submodule-notebook, to-merge

#1040 add bar `colour` option (notebook and std CLI)
  README.rst
  tqdm/completion.sh
  tqdm/notebook.py
  tqdm/std.py
  tqdm/tests/tests_tqdm.py
  tqdm/tqdm.1
Labels: c3-small, p3-enhancement, question/docs, submodule-notebook, to-merge
