Repository tqdm/tqdm, pull requests merged in 2020-07, with the labels that each got.

#1003 Fix test_min_iters() more clearly
  tqdm/tests/tests_tqdm.py
Labels: p3-enhancement, to-merge

#1004 add `tqdm.asyncio`
  .meta/.readme.rst
  README.rst
  examples/async_coroutines.py
  examples/coroutine_pipe.py
  tqdm/asyncio.py
  tqdm/std.py
  tqdm/tests/py37_asyncio.py
  tqdm/tests/tests_asyncio.py
Labels: c8-hard, help wanted, p3-enhancement, question/docs, submodule, synchronisation, to-fix

#1007 Accidental strongref
  tqdm/_monitor.py
Labels: c1-quick, p0-bug-critical, submodule, synchronisation, to-merge
