Repository tqdm/tqdm, pull requests merged in 2021-01, with the labels that each got.

#1107 next release v4.55.1
  CONTRIBUTING.md
  tqdm/std.py
Labels: c1-quick 🕐, p0-bug-critical ☢, submodule ⊂, to-merge ↰

#1006 Tqdm tk
  tqdm/gui.py
  tqdm/tk.py
Labels: need-feedback 📢, p3-enhancement 🔥, submodule ⊂, to-merge ↰, to-review 🔍

#1112 next release v4.56.0
  .meta/.readme.rst
  README.rst
  environment.yml
  tests/tests_gui.py
  tests/tests_rich.py
  tests/tests_tk.py
  tox.ini
  tqdm/gui.py
  tqdm/notebook.py
  tqdm/rich.py
  tqdm/tk.py
Labels: c8-hard 🕗, p3-enhancement 🔥, p3-framework ⚒, question/docs ‽, submodule ⊂, to-merge ↰
