Repository tqdm/tqdm, pull requests merged in 2021-03, with the labels that each got.

#1079 add `dask` submodule
  .meta/.readme.rst
  README.rst
  benchmarks/README.md
  environment.yml
  tests/tests_dask.py
  tox.ini
  tqdm/dask.py
  tqdm/gui.py
  tqdm/keras.py
  tqdm/rich.py
Labels: c1-quick 🕐, p3-enhancement 🔥, question/docs ‽, submodule ⊂, submodule-notebook 📓, synchronisation ⇶, to-merge ↰

#1132 next release: v4.59.0
  .github/FUNDING.yml
  .github/workflows/test.yml
  .mailmap
  .meta/.readme.rst
  .meta/requirements-build.txt
  .meta/requirements-test.txt
  CONTRIBUTING.md
  Makefile
  README.rst
  benchmarks/README.md
  environment.yml
  setup.cfg
  tests/py37_asyncio.py
  tests/tests_dask.py
  tests/tests_keras.py
  tox.ini
  tqdm/asyncio.py
  tqdm/auto.py
  tqdm/completion.sh
  tqdm/dask.py
  tqdm/gui.py
  tqdm/keras.py
  tqdm/notebook.py
  tqdm/rich.py
  tqdm/std.py
  tqdm/tqdm.1
Labels: c1-quick 🕐, p3-framework ⚒, question/docs ‽, to-merge ↰

#1136 Adding an asyncio.gather() replacement for tqdm
  tests/py37_asyncio.py
  tqdm/asyncio.py
  tqdm/auto.py
Labels: c1-quick 🕐, p3-enhancement 🔥, submodule ⊂, synchronisation ⇶, to-merge ↰
