Repository tqdm/tqdm, pull requests merged in 2021-06, with the labels that each got.

#1178 Fix typo
  .meta/.readme.rst
  README.rst
Labels: c1-quick 🕐, question/docs ‽, to-merge ↰

#1175 next release v4.61.1
  .github/workflows/comment-bot.yml
  .meta/.readme.rst
  README.rst
  tqdm/utils.py
Labels: c1-quick 🕐, p0-bug-critical ☢, question/docs ‽, to-merge ↰

#1184 Added AtributeError to address issue #1183
  tqdm/keras.py
Labels: c1-quick 🕐, p0-bug-critical ☢, submodule ⊂, to-merge ↰

#1189 telegram: add `delete()` when `leave=False`
  tqdm/contrib/telegram.py
  tqdm/rich.py
Labels: p3-enhancement 🔥, submodule ⊂, to-review 🔍
