Repository tqdm/tqdm, pull requests merged in 2021-05, with the labels that each got.

#1150 fix Display wrong epoch on Keras resume training
  tests/tests_keras.py
  tqdm/keras.py
Labels: c1-quick 🕐, p2-bug-warning ⚠, p3-enhancement 🔥, submodule ⊂, to-merge ↰

#1163 next release v4.61.0
  .meta/.readme.rst
  .pre-commit-config.yaml
  DEMO.ipynb
  README.rst
  tests/tests_contrib_logging.py
  tests/tests_keras.py
  tox.ini
  tqdm/contrib/discord.py
  tqdm/contrib/telegram.py
  tqdm/keras.py
Labels: p3-framework ⚒, submodule ⊂, to-merge ↰

#1174 Gracefully handle empty COLUMNS/LINES env vars on Linux.
  tqdm/utils.py
Labels: p0-bug-critical ☢
