Repository tqdm/tqdm, pull requests merged in 2021-07, with the labels that each got.

#1180 next release v4.61.2
  .github/workflows/test.yml
  .meta/.readme.rst
  DEMO.ipynb
  README.rst
  setup.cfg
  tqdm/asyncio.py
  tqdm/contrib/telegram.py
  tqdm/keras.py
  tqdm/rich.py
  tqdm/std.py
Labels: p0-bug-critical ☢, p3-enhancement 🔥, submodule ⊂, to-merge ↰

#1212 `asyncio.gather` API consistency with stdlib
  tests/py37_asyncio.py
  tqdm/asyncio.py
Labels: c1-quick 🕐, p0-bug-critical ☢, submodule ⊂

#1209 next release v4.62.0
  .github/FUNDING.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  tests/py37_asyncio.py
  tqdm/asyncio.py
  tqdm/utils.py
Labels: p3-framework ⚒, question/docs ‽, to-merge ↰
