Repository tqdm/tqdm, pull requests merged in 2021-08, with the labels that each got.

#1223 `contrib.telegram`: gracefully handle creation rate limit
  tqdm/contrib/telegram.py
Labels: c1-quick 🕐, p0-bug-critical ☢, submodule ⊂, to-merge ↰

#1191 logging: inherit output stream from existing handler
  tests/tests_contrib_logging.py
  tqdm/contrib/logging.py
Labels: p3-enhancement 🔥, submodule ⊂, to-merge ↰

#1207 Use weakref on tqdm instance in DisableOnWriteError
  tqdm/utils.py
Labels: p0-bug-critical ☢, to-merge ↰

#1222 next release v4.62.1
  tests/tests_contrib_logging.py
  tox.ini
  tqdm/contrib/__init__.py
  tqdm/contrib/bells.py
  tqdm/contrib/concurrent.py
  tqdm/contrib/discord.py
  tqdm/contrib/itertools.py
  tqdm/contrib/logging.py
  tqdm/contrib/telegram.py
  tqdm/contrib/utils_worker.py
  tqdm/utils.py
Labels: p0-bug-critical ☢, p3-enhancement 🔥, submodule ⊂, to-merge ↰

#1233 fix `contrib.concurrent` with generators
  tqdm/contrib/concurrent.py
Labels: p0-bug-critical ☢, to-merge ↰, c1-quick 🕐

#1229 next release v4.62.2
  tqdm/contrib/concurrent.py
  tqdm/notebook.py
Labels: p0-bug-critical ☢, submodule-notebook 📓
