Repository tqdm/tqdm, pull requests merged in 2021-02, with the labels that each got.

#1113 next release v4.56.1
  .github/workflows/test.yml
  .gitignore
  .mailmap
  .meta/.readme.rst
  .meta/.tqdm.1.md
  .pre-commit-config.yaml
  DEMO.ipynb
  Dockerfile
  LICENCE
  Makefile
  README.rst
  images/slides.jpg
  images/tqdm-jupyter-1.gif
  images/tqdm-jupyter-2.gif
  images/tqdm-jupyter-3.gif
  images/video.jpg
  setup.cfg
  tests/tests_tqdm.py
  tox.ini
  tqdm/std.py
  tqdm/tqdm.1
Labels: c1-quick 🕐, p0-bug-critical ☢, question/docs ‽, to-merge ↰

#1126 next release: v4.56.2
  tests/tests_tqdm.py
  tqdm/contrib/discord.py
  tqdm/contrib/telegram.py
  tqdm/notebook.py
  tqdm/std.py
Labels: c1-quick 🕐, p0-bug-critical ☢, submodule ⊂, submodule-notebook 📓, to-merge ↰

#960 `DummyTqdmFile` line buffering
  tests/tests_tqdm.py
  tqdm/contrib/__init__.py
Labels: c1-quick 🕐, p2-bug-warning ⚠, p3-enhancement 🔥, to-merge ↰

#1127 next release v4.57.0
  .coveragerc
  .gitattributes
  .github/workflows/test.yml
  .meta/.readme.rst
  .meta/mksnap.py
  DEMO.ipynb
  examples/7zx.py
  examples/parallel_bars.py
  examples/tqdm_wget.py
  setup.cfg
  setup.py
  tests/tests_main.py
  tests/tests_tqdm.py
  tox.ini
  tqdm/auto.py
  tqdm/cli.py
  tqdm/contrib/__init__.py
  tqdm/std.py
  tqdm/utils.py
Labels: p2-bug-warning ⚠, p3-enhancement 🔥, p3-framework ⚒, question/docs ‽, to-merge ↰

#836 Allow hiding progressbar until some time interval has elapsed.
  tests/tests_tqdm.py
  tqdm/std.py
Labels: c1-quick 🕐, p3-enhancement 🔥, to-merge ↰
