Repository tqdm/tqdm, pull requests merged in 2022-03, with the labels that each got.

#1248 Ensure that stderr/stdout has flush attr before calling it
  tqdm/std.py
Labels: p0-bug-critical ☢, to-merge ↰, c1-quick 🕐

#1301 docs: fix typo
  tqdm/std.py
Labels: question/docs ‽

#1299 docs: fix custom callback example typo
  .meta/.readme.rst
  README.rst
Labels: question/docs ‽, to-merge ↰
