Repository tqdm/tqdm, pull requests merged in 2022-04, with the labels that each got.

#1309 autonotebook: re-enable VSCode
  tqdm/autonotebook.py
Labels: to-merge ↰, c1-quick 🕐

#1311 next release v4.63.2
  .meta/.readme.rst
  README.rst
  environment.yml
  tqdm/autonotebook.py
  tqdm/rich.py
  tqdm/std.py
Labels: submodule ⊂, to-merge ↰, p3-framework ⚒

#1313 add contrib.slack
  .meta/.readme.rst
  README.rst
  environment.yml
  setup.cfg
  tqdm/contrib/bells.py
  tqdm/contrib/discord.py
  tqdm/contrib/slack.py
Labels: p3-enhancement 🔥, submodule ⊂, to-merge ↰, c3-small 🕒
